name: Create open.ttl

on:
  workflow_dispatch:

jobs:
  turtle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install raptor2-utils and groovy
        run: sudo apt install raptor2-utils groovy

      - name: Generate a new open.ttl
        run: |
          bash fetchData.sh
          make validation
          make open.ttl

      - name: Generate the Shex validation reports
        run: |
          bash fetchShapes.sh
          make all

      - name: Commit report
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'actions@github.com'
          git add open.txt open.ttl *.json
          if git diff --exit-code --staged; then
              echo "No changes"
          else
              git commit -m 'Updated service open landscape data'
              git push
          fi
